repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3

  # - repo: https://github.com/pre-commit/mirrors-clang-format
  #   rev: v15.0.7
  #   hooks:
  #     - id: clang-format

  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: v4.1.1
  #   hooks:
  #     - id: prettier
  #       files: \.md$
